//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLibrary.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the request: .
        /// </summary>
        public static string Errors_AuthHeader_FailedSendingRequest {
            get {
                return ResourceManager.GetString("Errors_AuthHeader_FailedSendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing user identity..
        /// </summary>
        public static string Errors_AuthService_ClearingUserIdentity {
            get {
                return ResourceManager.GetString("Errors_AuthService_ClearingUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to view:.
        /// </summary>
        public static string Errors_NavigatingToView {
            get {
                return ResourceManager.GetString("Errors_NavigatingToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to window: .
        /// </summary>
        public static string Errors_NavigatingToWindow {
            get {
                return ResourceManager.GetString("Errors_NavigatingToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from server..
        /// </summary>
        public static string Errors_UserService_InvalidResponse {
            get {
                return ResourceManager.GetString("Errors_UserService_InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string Errors_UserService_LoginFailed {
            get {
                return ResourceManager.GetString("Errors_UserService_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LogIn_Email {
            get {
                return ResourceManager.GetString("LogIn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn_LogInButton {
            get {
                return ResourceManager.GetString("LogIn_LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogIn_Password {
            get {
                return ResourceManager.GetString("LogIn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health check failed. Please check your API and Database connection..
        /// </summary>
        public static string Splash_APIChecksFailed {
            get {
                return ResourceManager.GetString("Splash_APIChecksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking API....
        /// </summary>
        public static string Splash_CheckingAPI {
            get {
                return ResourceManager.GetString("Splash_CheckingAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking DB....
        /// </summary>
        public static string Splash_CheckingDB {
            get {
                return ResourceManager.GetString("Splash_CheckingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Splash_Loading {
            get {
                return ResourceManager.GetString("Splash_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Splash_LoadingComplete {
            get {
                return ResourceManager.GetString("Splash_LoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string Validators_Email_Invalid {
            get {
                return ResourceManager.GetString("Validators_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at most 20 characters long..
        /// </summary>
        public static string Validators_Password_MaxChars {
            get {
                return ResourceManager.GetString("Validators_Password_MaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string Validators_Password_MinChars {
            get {
                return ResourceManager.GetString("Validators_Password_MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty..
        /// </summary>
        public static string Validators_Password_NullOrEmpty {
            get {
                return ResourceManager.GetString("Validators_Password_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string Validators_Password_OneLowercase {
            get {
                return ResourceManager.GetString("Validators_Password_OneLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string Validators_Password_OneUppercase {
            get {
                return ResourceManager.GetString("Validators_Password_OneUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters and digits..
        /// </summary>
        public static string Validators_Username_LettersAndDigits {
            get {
                return ResourceManager.GetString("Validators_Username_LettersAndDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at most 30 characters long..
        /// </summary>
        public static string Validators_Username_MaxChars {
            get {
                return ResourceManager.GetString("Validators_Username_MaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 characters long..
        /// </summary>
        public static string Validators_Username_MinChars {
            get {
                return ResourceManager.GetString("Validators_Username_MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be null or empty..
        /// </summary>
        public static string Validators_Username_NullOrEmpty {
            get {
                return ResourceManager.GetString("Validators_Username_NullOrEmpty", resourceCulture);
            }
        }
    }
}
