//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibrary.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLibrary.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Book_Details_Author {
            get {
                return ResourceManager.GetString("Book_Details_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower:.
        /// </summary>
        public static string Book_Details_Borrower {
            get {
                return ResourceManager.GetString("Book_Details_Borrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Book_Details_Description {
            get {
                return ResourceManager.GetString("Book_Details_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string Book_Details_Genre {
            get {
                return ResourceManager.GetString("Book_Details_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string Book_Details_ID {
            get {
                return ResourceManager.GetString("Book_Details_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        public static string Book_Details_ISBN {
            get {
                return ResourceManager.GetString("Book_Details_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string Book_Details_Publisher {
            get {
                return ResourceManager.GetString("Book_Details_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Book_Details_Title {
            get {
                return ResourceManager.GetString("Book_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching book by ID..
        /// </summary>
        public static string BookService_Errors_ErrorFetchingBookByID {
            get {
                return ResourceManager.GetString("BookService_Errors_ErrorFetchingBookByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching book by ISBN..
        /// </summary>
        public static string BookService_Errors_ErrorFetchingBookByISBN {
            get {
                return ResourceManager.GetString("BookService_Errors_ErrorFetchingBookByISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book borrow failed..
        /// </summary>
        public static string Borrows_Failed_To_Borrow {
            get {
                return ResourceManager.GetString("Borrows_Failed_To_Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason the book was not selected..
        /// </summary>
        public static string Borrows_Missing_Book {
            get {
                return ResourceManager.GetString("Borrows_Missing_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book borrowed successfully..
        /// </summary>
        public static string Borrows_Successfully_Borrowed {
            get {
                return ResourceManager.GetString("Borrows_Successfully_Borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID field cannot be empty..
        /// </summary>
        public static string Borrows_Validations_EmptyID {
            get {
                return ResourceManager.GetString("Borrows_Validations_EmptyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid ID..
        /// </summary>
        public static string Borrows_Validations_InvalidID {
            get {
                return ResourceManager.GetString("Borrows_Validations_InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        public static string Buttons_Borrow {
            get {
                return ResourceManager.GetString("Buttons_Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Buttons_Find {
            get {
                return ResourceManager.GetString("Buttons_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Buttons_Return {
            get {
                return ResourceManager.GetString("Buttons_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomDialog_Cancel {
            get {
                return ResourceManager.GetString("CustomDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CustomDialog_Confirm {
            get {
                return ResourceManager.GetString("CustomDialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CustomDialog_OK {
            get {
                return ResourceManager.GetString("CustomDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        public static string CustomDialog_Title_Fail {
            get {
                return ResourceManager.GetString("CustomDialog_Title_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        public static string CustomDialog_Title_Success {
            get {
                return ResourceManager.GetString("CustomDialog_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API response was null..
        /// </summary>
        public static string Errors_Api_NullResponse {
            get {
                return ResourceManager.GetString("Errors_Api_NullResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the request: .
        /// </summary>
        public static string Errors_AuthHeader_FailedSendingRequest {
            get {
                return ResourceManager.GetString("Errors_AuthHeader_FailedSendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing user identity..
        /// </summary>
        public static string Errors_AuthService_ClearingUserIdentity {
            get {
                return ResourceManager.GetString("Errors_AuthService_ClearingUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is already returned, or not borrowed at all..
        /// </summary>
        public static string Errors_Book_Already_Returned {
            get {
                return ResourceManager.GetString("Errors_Book_Already_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get borrow from the DB..
        /// </summary>
        public static string Errors_Borrows_FailedToGetBorrow {
            get {
                return ResourceManager.GetString("Errors_Borrows_FailedToGetBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing the app..
        /// </summary>
        public static string Errors_ClosingApp {
            get {
                return ResourceManager.GetString("Errors_ClosingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to view:.
        /// </summary>
        public static string Errors_NavigatingToView {
            get {
                return ResourceManager.GetString("Errors_NavigatingToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to window: .
        /// </summary>
        public static string Errors_NavigatingToWindow {
            get {
                return ResourceManager.GetString("Errors_NavigatingToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN cannot be empty..
        /// </summary>
        public static string Errors_Receipt_EmptyISBN {
            get {
                return ResourceManager.GetString("Errors_Receipt_EmptyISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found with given ISBN..
        /// </summary>
        public static string Errors_Receipt_ISBNNotFound {
            get {
                return ResourceManager.GetString("Errors_Receipt_ISBNNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items in the receipt. Please add items before finalizing the sale..
        /// </summary>
        public static string Errors_Receipt_ZeroOrders {
            get {
                return ResourceManager.GetString("Errors_Receipt_ZeroOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from server..
        /// </summary>
        public static string Errors_UserService_InvalidResponse {
            get {
                return ResourceManager.GetString("Errors_UserService_InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string Errors_UserService_LoginFailed {
            get {
                return ResourceManager.GetString("Errors_UserService_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is invalid or file does not exist..
        /// </summary>
        public static string FileService_Errors_InvalidFilePath {
            get {
                return ResourceManager.GetString("FileService_Errors_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the maximum limit of 5MB..
        /// </summary>
        public static string FileService_Errors_InvalidFileSize {
            get {
                return ResourceManager.GetString("FileService_Errors_InvalidFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Allowed types are: .
        /// </summary>
        public static string FileService_Errors_InvalidFileType {
            get {
                return ResourceManager.GetString("FileService_Errors_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        public static string Home_BorrowBooks {
            get {
                return ResourceManager.GetString("Home_BorrowBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Home_ReturnBooks {
            get {
                return ResourceManager.GetString("Home_ReturnBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Home_Sell {
            get {
                return ResourceManager.GetString("Home_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LogIn_Email {
            get {
                return ResourceManager.GetString("LogIn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn_LogInButton {
            get {
                return ResourceManager.GetString("LogIn_LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogIn_Password {
            get {
                return ResourceManager.GetString("LogIn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book is either not found, or out of stock..
        /// </summary>
        public static string Receipt_AddNewItem_NotFoundOrNotAvailable {
            get {
                return ResourceManager.GetString("Receipt_AddNewItem_NotFoundOrNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Recipe_Header_ISBN {
            get {
                return ResourceManager.GetString("Recipe_Header_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Recipe_Header_Name {
            get {
                return ResourceManager.GetString("Recipe_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Recipe_Header_Price {
            get {
                return ResourceManager.GetString("Recipe_Header_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Recipe_Header_Quantity {
            get {
                return ResourceManager.GetString("Recipe_Header_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Recipe_Header_Total {
            get {
                return ResourceManager.GetString("Recipe_Header_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book returned successfully..
        /// </summary>
        public static string Return_Book_Returned_Successfully {
            get {
                return ResourceManager.GetString("Return_Book_Returned_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID cannot be null..
        /// </summary>
        public static string Sell_Validations_ID_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Sell_Validations_ID_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN cannot be null..
        /// </summary>
        public static string Sell_Validations_ISBN_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Sell_Validations_ISBN_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item with such ID/ISBN..
        /// </summary>
        public static string Sell_Validations_ItemNotFound {
            get {
                return ResourceManager.GetString("Sell_Validations_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cannot be null..
        /// </summary>
        public static string Sell_Validations_NullOrder {
            get {
                return ResourceManager.GetString("Sell_Validations_NullOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be at least 1..
        /// </summary>
        public static string Sell_Validations_NullQuantity {
            get {
                return ResourceManager.GetString("Sell_Validations_NullQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health check failed. Please check your API and Database connection..
        /// </summary>
        public static string Splash_APIChecksFailed {
            get {
                return ResourceManager.GetString("Splash_APIChecksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking API....
        /// </summary>
        public static string Splash_CheckingAPI {
            get {
                return ResourceManager.GetString("Splash_CheckingAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking DB....
        /// </summary>
        public static string Splash_CheckingDB {
            get {
                return ResourceManager.GetString("Splash_CheckingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Splash_Loading {
            get {
                return ResourceManager.GetString("Splash_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Splash_LoadingComplete {
            get {
                return ResourceManager.GetString("Splash_LoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book ID.
        /// </summary>
        public static string TextBoxes_BookID {
            get {
                return ResourceManager.GetString("TextBoxes_BookID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Book ID..
        /// </summary>
        public static string Validators_BookId_Invalid {
            get {
                return ResourceManager.GetString("Validators_BookId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string Validators_Email_Invalid {
            get {
                return ResourceManager.GetString("Validators_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at most 20 characters long..
        /// </summary>
        public static string Validators_Password_MaxChars {
            get {
                return ResourceManager.GetString("Validators_Password_MaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string Validators_Password_MinChars {
            get {
                return ResourceManager.GetString("Validators_Password_MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty..
        /// </summary>
        public static string Validators_Password_NullOrEmpty {
            get {
                return ResourceManager.GetString("Validators_Password_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        public static string Validators_Password_OneLowercase {
            get {
                return ResourceManager.GetString("Validators_Password_OneLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string Validators_Password_OneUppercase {
            get {
                return ResourceManager.GetString("Validators_Password_OneUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters and digits..
        /// </summary>
        public static string Validators_Username_LettersAndDigits {
            get {
                return ResourceManager.GetString("Validators_Username_LettersAndDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at most 30 characters long..
        /// </summary>
        public static string Validators_Username_MaxChars {
            get {
                return ResourceManager.GetString("Validators_Username_MaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 characters long..
        /// </summary>
        public static string Validators_Username_MinChars {
            get {
                return ResourceManager.GetString("Validators_Username_MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be null or empty..
        /// </summary>
        public static string Validators_Username_NullOrEmpty {
            get {
                return ResourceManager.GetString("Validators_Username_NullOrEmpty", resourceCulture);
            }
        }
    }
}
